---
title: 'Excepciones: Expresión failwith'
description: Obtenga información sobre cómo la función ' failwith ' F# genera una excepción.
ms.date: 05/16/2016
ms.openlocfilehash: f2c86362d5bdde7bab55751f019965a5f4ca6236
ms.sourcegitcommit: f20dd18dbcf2275513281f5d9ad7ece6a62644b4
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 07/30/2019
ms.locfileid: "68630329"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="59215-103">Excepciones: Expresión failwith</span><span class="sxs-lookup"><span data-stu-id="59215-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="59215-104">La `failwith` función genera una F# excepción.</span><span class="sxs-lookup"><span data-stu-id="59215-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="59215-105">Sintaxis</span><span class="sxs-lookup"><span data-stu-id="59215-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="59215-106">Comentarios</span><span class="sxs-lookup"><span data-stu-id="59215-106">Remarks</span></span>

<span data-ttu-id="59215-107">La *cadena de mensaje de error* en la sintaxis anterior es una cadena literal o un valor de tipo `string`.</span><span class="sxs-lookup"><span data-stu-id="59215-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="59215-108">Se convierte en `Message` la propiedad de la excepción.</span><span class="sxs-lookup"><span data-stu-id="59215-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="59215-109">La `failwith` excepción generada por es una `System.Exception` excepción, que es una referencia que tiene el nombre `Failure` en F# el código.</span><span class="sxs-lookup"><span data-stu-id="59215-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="59215-110">En el código siguiente se muestra el uso `failwith` de para producir una excepción.</span><span class="sxs-lookup"><span data-stu-id="59215-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](~/samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="59215-111">Vea también</span><span class="sxs-lookup"><span data-stu-id="59215-111">See also</span></span>

- [<span data-ttu-id="59215-112">Control de excepciones</span><span class="sxs-lookup"><span data-stu-id="59215-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="59215-113">Tipos de excepción</span><span class="sxs-lookup"><span data-stu-id="59215-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="59215-114">Excepciones: La `try...with` expresión</span><span class="sxs-lookup"><span data-stu-id="59215-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="59215-115">Excepciones: La `try...finally` expresión</span><span class="sxs-lookup"><span data-stu-id="59215-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- <span data-ttu-id="59215-116">[Exceptions: the `raise` Function](the-raise-function.md) (Excepciones: la función `raise`)</span><span class="sxs-lookup"><span data-stu-id="59215-116">[Exceptions: the `raise` Function](the-raise-function.md)</span></span>
