---
title: 'Excepciones: Función failwith'
description: Obtenga información sobre cómo la función 'failwith' genera un F# excepción.
ms.date: 05/16/2016
ms.openlocfilehash: 08107966ddc2f55625347deb92d224b286df7761
ms.sourcegitcommit: 8699383914c24a0df033393f55db3369db728a7b
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 05/15/2019
ms.locfileid: "65641948"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="3694c-103">Excepciones: Función failwith</span><span class="sxs-lookup"><span data-stu-id="3694c-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="3694c-104">El `failwith` función genera una F# excepción.</span><span class="sxs-lookup"><span data-stu-id="3694c-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="3694c-105">Sintaxis</span><span class="sxs-lookup"><span data-stu-id="3694c-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="3694c-106">Comentarios</span><span class="sxs-lookup"><span data-stu-id="3694c-106">Remarks</span></span>

<span data-ttu-id="3694c-107">El *cadena de mensaje de error* en la sintaxis anterior es una cadena literal o un valor de tipo `string`.</span><span class="sxs-lookup"><span data-stu-id="3694c-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="3694c-108">Se convierte en el `Message` propiedad de la excepción.</span><span class="sxs-lookup"><span data-stu-id="3694c-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="3694c-109">La excepción generada por `failwith` es un `System.Exception` excepción, que es una referencia que tiene el nombre `Failure` en F# código.</span><span class="sxs-lookup"><span data-stu-id="3694c-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="3694c-110">El código siguiente muestra el uso de `failwith` para producir una excepción.</span><span class="sxs-lookup"><span data-stu-id="3694c-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="3694c-111">Vea también</span><span class="sxs-lookup"><span data-stu-id="3694c-111">See also</span></span>

- [<span data-ttu-id="3694c-112">Control de excepciones</span><span class="sxs-lookup"><span data-stu-id="3694c-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="3694c-113">Tipos de excepción</span><span class="sxs-lookup"><span data-stu-id="3694c-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="3694c-114">Excepciones: El `try...with` expresión</span><span class="sxs-lookup"><span data-stu-id="3694c-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="3694c-115">Excepciones: El `try...finally` expresión</span><span class="sxs-lookup"><span data-stu-id="3694c-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- <span data-ttu-id="3694c-116">[Exceptions: the `raise` Function](the-raise-function.md) (Excepciones: la función `raise`)</span><span class="sxs-lookup"><span data-stu-id="3694c-116">[Exceptions: the `raise` Function](the-raise-function.md)</span></span>
