---
title: Error del compilador CS0724
ms.date: 07/20/2015
f1_keywords:
- CS0724
helpviewer_keywords:
- CS0724
ms.assetid: bcdb2017-7a43-4242-b4e2-a1ae03d6d73f
ms.openlocfilehash: feae6b666067e652e1021b1f173bab56c7a27dc0
ms.sourcegitcommit: ad800f019ac976cb669e635fb0ea49db740e6890
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/29/2019
ms.locfileid: "73039385"
---
# <a name="compiler-error-cs0724"></a><span data-ttu-id="4f6bb-102">Error del compilador CS0724</span><span class="sxs-lookup"><span data-stu-id="4f6bb-102">Compiler Error CS0724</span></span>

<span data-ttu-id="4f6bb-103">No se permite una instrucción throw sin argumentos en una cláusula finally anidada en la cláusula catch más cercana</span><span class="sxs-lookup"><span data-stu-id="4f6bb-103">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>

## <a name="example"></a><span data-ttu-id="4f6bb-104">Ejemplo</span><span class="sxs-lookup"><span data-stu-id="4f6bb-104">Example</span></span>

<span data-ttu-id="4f6bb-105">En el ejemplo siguiente se genera error CS0724 debido a la instrucción `throw` dentro del bloque de cláusulas `finally`:</span><span class="sxs-lookup"><span data-stu-id="4f6bb-105">The following example generates CS0724 because of the `throw` statement inside the `finally` clause block:</span></span>

```csharp  
// CS0724.cs  
using System;  
  
class Program
{
    static void Test()
    {
        try
        {
            throw new Exception();
        }
        catch
        {
            try
            {
            }
            finally
            {
                throw; // CS0724
            }
        }
    }

    static void Main()
    {
    }
}
```
