---
title: La instrucción 'Throw' no puede omitir el operando fuera de una instrucción 'Catch' o dentro de una instrucción 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: f87c705a8672ba79124c618fbd28e2ef79136b6f
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 03/15/2019
ms.locfileid: "58026247"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="295df-102">La instrucción 'Throw' no puede omitir el operando fuera de una instrucción 'Catch' o dentro de una instrucción 'Finally'</span><span class="sxs-lookup"><span data-stu-id="295df-102">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>
<span data-ttu-id="295df-103">Las instrucciones`Throw` fuera de una instrucción `Catch` deben facilitar el nombre de un objeto de excepción.</span><span class="sxs-lookup"><span data-stu-id="295df-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="295df-104">**Identificador de error:** BC30666</span><span class="sxs-lookup"><span data-stu-id="295df-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="295df-105">Para corregir este error</span><span class="sxs-lookup"><span data-stu-id="295df-105">To correct this error</span></span>  
  
1.  <span data-ttu-id="295df-106">Especifique el nombre de un objeto de excepción que derive de `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="295df-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2.  <span data-ttu-id="295df-107">Reestructure el código para que la instrucción `Throw` se encuentre dentro de un bloque `Catch` .</span><span class="sxs-lookup"><span data-stu-id="295df-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="295df-108">Vea también</span><span class="sxs-lookup"><span data-stu-id="295df-108">See also</span></span>

- [<span data-ttu-id="295df-109">Throw (instrucción)</span><span class="sxs-lookup"><span data-stu-id="295df-109">Throw Statement</span></span>](../../visual-basic/language-reference/statements/throw-statement.md)
- [<span data-ttu-id="295df-110">Try...Catch...Finally (instrucción)</span><span class="sxs-lookup"><span data-stu-id="295df-110">Try...Catch...Finally Statement</span></span>](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="295df-111">Controlar y generar excepciones en .NET</span><span class="sxs-lookup"><span data-stu-id="295df-111">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
